version: '3.8'

services:
  orchestrator:
    build:
      context: ./services/orchestrator
    container_name: orchestrator
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default